### ISSUE TITLE
Регистрация зависимости Commands.Rotate в IoC.

### ISSUE THREAD

**Issue by terracodum** [smnk-1/OOPnD#23]
9. Зарегистрировать зависимость "Commands.Rotate" в IoC, с помощью которой можно разрешить команду MoveCommand по игровому объекту. Для регистрации зависимости определить отдельную команду с префиксом RegisterIoCDependency:

Исполнитель: Харлов Никита ФИТ-232

**Comment by zaryanezrya** [comment]
LGTM
