### ISSUE TITLE
Угол на плоскости.

### ISSUE THREAD

**Issue by terracodum** [smnk-1/OOPnD#25]
Для представления угла наклона к оси OX игрового объекта реализовать класс Angle. Внутри Angle представлен как рациональное число, причем знаменатель у всех углов будет одинаковый (его можно сделать статическим полем). Для угла должна быть реализована операция сложения и должна быть возможность вычисления синуса и косинуса от Angle без предварительного явного приведения к типу Double: Math.Cos(angle).

Исполнитель Харлов Никита ФИТ-232

**Comment by zaryanezrya** [comment]
LGTM
